trigger:
  batch: true
  paths:
    include:
      - 'B/B-1/*'

pr:
  paths:
    include:
    - B/B-1/*
    - B/B-2/*
    exclude:
    - A/*
    
pool: 
  vmImage: 'ubuntu-latest'

steps:
 - script: echo "Hola Mundo B1"
 


