trigger:
  batch: true
  branches:
    include:
      - '*'
  paths:
    include:
      - 'A/*'
      
pr:
  paths:
    include:
    - A/*
    exclude:
    - B/B-1/*
    
pool: 
  vmImage: 'ubuntu-latest'

steps:
 - script: echo "Hola Mundo A"
 


