trigger:
  batch: true
  paths:
    include:
      - 'A/*'

pr:
  paths:
    include:
    - A/*
    exclude:
    - B/B-1/*
    - B/B-2/*
    
    
pool: 
  vmImage: 'ubuntu-latest'

steps:
 - script: echo "Hola Mundo A"
 


